version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /js/(.*)
  static_files: js/\1
  upload: js/.*

- url: /help.html
  static_files: help.html
  upload: help.html
- url: /web.html
  static_files: web.html
  upload: web.html
- url: /web.unity3d
  static_files: web.unity3d
  upload: web.unity3d
- url: /DailyPlanner
  static_files: /DailyPlanner/index.html
  upload: /DailyPlanner/index.html